basePath: /survey
definitions:
  schemas.PostSurveyLookingForMentorPayload:
    properties:
      currentExperience:
        type: string
      mentorDescription:
        type: string
      skillsToLearn:
        type: string
      userEmail:
        type: string
    required:
    - currentExperience
    - mentorDescription
    - skillsToLearn
    - userEmail
    type: object
  schemas.PostSurveyUserIntroPayload:
    properties:
      deviceId:
        type: string
      preferredInterfaceLanguage:
        type: string
      role:
        type: string
      source:
        type: string
      studentExperience:
        type: string
      studentGoals:
        type: string
      whyRegistered:
        type: string
    required:
    - deviceId
    - preferredInterfaceLanguage
    - role
    - source
    - studentExperience
    - studentGoals
    - whyRegistered
    type: object
info:
  contact: {}
  title: Masters way survey API
  version: "1.0"
paths:
  /dev/reset-db:
    get:
      description: resets db
      responses:
        "204":
          description: No Content
      summary: resets db
      tags:
      - dev
  /looking-for-mentor:
    post:
      consumes:
      - application/json
      description: Post survey looking for mentor
      operationId: survey-looking-for-mentor
      parameters:
      - description: query params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/schemas.PostSurveyLookingForMentorPayload'
      produces:
      - application/json
      responses:
        "204":
          description: No Content
      summary: Post survey looking for mentor
      tags:
      - survey
  /user-intro:
    post:
      consumes:
      - application/json
      description: Post survey user intro
      operationId: survey-user-intro
      parameters:
      - description: query params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/schemas.PostSurveyUserIntroPayload'
      produces:
      - application/json
      responses:
        "204":
          description: No Content
      summary: Post survey user intro
      tags:
      - survey
swagger: "2.0"
