version: "3.9"
services:
  mail-postgres:
    image: postgres:16.2
    container_name: mail-postgres
    ports:
      - "5437:5432"
    volumes:
      - mail-db:/var/lib/postgresql/data
    env_file:
      - ./.env

volumes:
  mail-db: