basePath: /notification
definitions:
  mw-notification-bff_internal_schemas.GetNotificationListResponse:
    properties:
      notifications:
        items:
          $ref: '#/definitions/mw-notification-bff_internal_schemas.NotificationResponse'
        type: array
      totalSize:
        type: integer
      unreadSize:
        type: integer
    required:
    - notifications
    - totalSize
    - unreadSize
    type: object
  mw-notification-bff_internal_schemas.GetNotificationSettingListResponse:
    properties:
      NotificationSettings:
        items:
          $ref: '#/definitions/mw-notification-bff_internal_schemas.NotificationSettingResponse'
        type: array
    required:
    - NotificationSettings
    type: object
  mw-notification-bff_internal_schemas.NotificationResponse:
    properties:
      createdAt:
        type: string
      description:
        type: string
      isRead:
        type: boolean
      nature:
        type: string
      url:
        type: string
      userUuid:
        type: string
      uuid:
        type: string
    required:
    - createdAt
    - description
    - isRead
    - nature
    - url
    - userUuid
    - uuid
    type: object
  mw-notification-bff_internal_schemas.NotificationSettingResponse:
    properties:
      channel:
        type: string
      isEnabled:
        type: boolean
      nature:
        type: string
      userUuid:
        type: string
      uuid:
        type: string
    required:
    - channel
    - isEnabled
    - nature
    - userUuid
    - uuid
    type: object
  mw-notification-bff_internal_schemas.UpdateNotificationPayload:
    properties:
      isRead:
        type: boolean
    required:
    - isRead
    type: object
  mw-notification-bff_internal_schemas.UpdateNotificationSettingPayload:
    properties:
      isEnabled:
        type: boolean
    required:
    - isEnabled
    type: object
info:
  contact: {}
  title: Masters way notification-bff API
  version: "1.0"
paths:
  /notificationSettings:
    get:
      consumes:
      - application/json
      operationId: get-notificationSetting-list
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/mw-notification-bff_internal_schemas.GetNotificationSettingListResponse'
      summary: Get notificationSetting list by user id
      tags:
      - notificationSetting
  /notificationSettings/{notificationSettingId}:
    patch:
      consumes:
      - application/json
      operationId: update-notificationSetting
      parameters:
      - description: query params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/mw-notification-bff_internal_schemas.UpdateNotificationSettingPayload'
      - description: notification id
        in: path
        name: notificationSettingId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/mw-notification-bff_internal_schemas.NotificationSettingResponse'
      summary: Update notificationSetting by id
      tags:
      - notificationSetting
  /notifications:
    get:
      consumes:
      - application/json
      operationId: get-notification-list
      parameters:
      - description: Page number for pagination - 1 by default
        in: query
        name: page
        type: integer
      - description: Number of items per page - 50 by default
        in: query
        name: limit
        type: integer
      - description: Get only new notifications - false by default
        in: query
        name: isOnlyNew
        type: boolean
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/mw-notification-bff_internal_schemas.GetNotificationListResponse'
      summary: Get notification list by user id
      tags:
      - notification
  /notifications/{notificationId}:
    patch:
      consumes:
      - application/json
      operationId: update-notification
      parameters:
      - description: query params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/mw-notification-bff_internal_schemas.UpdateNotificationPayload'
      - description: notification id
        in: path
        name: notificationId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/mw-notification-bff_internal_schemas.NotificationResponse'
      summary: Update notification by id
      tags:
      - notification
swagger: "2.0"
