basePath: /mail
definitions:
  schemas.SendMailResponse:
    properties:
      fromEmail:
        type: string
      htmlMessage:
        type: string
      id:
        type: string
      message:
        type: string
      recipients:
        items:
          type: string
        type: array
      subject:
        type: string
    required:
    - fromEmail
    - id
    - recipients
    - subject
    type: object
info:
  contact: {}
  title: Masters way mail API
  version: "1.0"
paths:
  /dev/reset-db:
    get:
      description: resets db
      responses:
        "204":
          description: No Content
      summary: resets db
      tags:
      - dev
  /mail:
    post:
      consumes:
      - application/json
      description: Sending messages to recipients by smtp and saving the log of the
        sent email
      operationId: send-email
      parameters:
      - description: Subject of the email
        in: body
        name: subject
        required: true
        schema:
          type: string
      - description: Recipient email addresses
        in: body
        name: to
        required: true
        schema:
          type: array
      - description: CC email addresses
        in: body
        name: cc
        schema:
          type: array
      - description: BCC email addresses
        in: body
        name: bcc
        schema:
          type: array
      - description: Plain text message
        in: body
        name: message
        schema:
          type: string
      - description: HTML message
        in: body
        name: html_message
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schemas.SendMailResponse'
      summary: Sending messages to recipients and save logs
      tags:
      - mail
swagger: "2.0"
